config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#splash"
  resources :extensions do
    resources :updates
  end
  get '/splash' => 'pages#splash'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        cannot :manage, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/extension.rb
class Extension < ApplicationRecord
  has_many :updates, :dependent => :destroy
  validates :name, :presence => true
  validates :url, :presence => true
  scope :alphabetical, -> { order(name: :ASC) }
  scope :last_updated, -> { includes(:updates).order('updates.date DESC') }
end

app/models/update.rb
class Update < ApplicationRecord
  belongs_to :extension
  validates_uniqueness_of :version
  scope :only_majors, -> { where(major: true).order(version: :DESC) }
  scope :unreviewed, -> { where(reviewed: false).order(version: :DESC) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end


end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
  before_action :set_extension, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /extensions
  # GET /extensions.json
  def index
    @order = params[:order] || "last_updated"
    @reviewed = params[:reviewed] || "unreviewed"
    @type = params[:type] || "major"
    @sort_hash = 
    if @order == "last_updated"
      @extensions = Extension.last_updated.includes(:updates)
    elsif @order == "alpha"
      @extensions = Extension.alphabetical.includes(:updates)
    end
  end

  # GET /extensions/1
  # GET /extensions/1.json
  def show
  end

  # GET /extensions/new
  def new
    @extension = Extension.new
  end

  # GET /extensions/1/edit
  def edit
  end

  # POST /extensions
  # POST /extensions.json
  def create
    @extension = Extension.new(extension_params)

    respond_to do |format|
      if @extension.save
        format.js
        format.html { redirect_to @extension, notice: 'Extension was successfully created.' }
        format.json { render :show, status: :created, location: @extension }
      else
        format.html { render :new }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extensions/1
  # PATCH/PUT /extensions/1.json
  def update
    respond_to do |format|
      if @extension.update(extension_params)
        format.js
        format.html { redirect_to @extension, notice: 'Extension was successfully updated.' }
        format.json { render :show, status: :ok, location: @extension }
      else
        format.html { render :edit }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extensions/1
  # DELETE /extensions/1.json
  def destroy
    @extension.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to extensions_url, notice: 'Extension was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extension
      @extension = Extension.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extension_params
      params.require(:extension).permit(:name, :url, :site)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash
    if current_user.admin?
      redirect_to(extensions_path)
    end
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(update_params)

    respond_to do |format|
      if @update.save
        format.html { redirect_to @update, notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    respond_to do |format|
      puts params
      if @update.update(update_params)
        format.js
        format.html { redirect_to [@update.extension, @update], notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to updates_url, notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_params
      params.require(:update).permit(:version, :date, :overview, :extension_id, :reviewed, :major)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/extensions_helper.rb
module ExtensionsHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/extensions/_checkbox.html.erb
      <% if update.reviewed == true %>
        <%= link_to '<i class="far fa-check-square"></i>'.html_safe, extension_update_path(update.extension, update, :update => { :reviewed => false }), :method => :put, :remote => true %>
      <% else %>
        <%= link_to '<i class="far fa-square"></i>'.html_safe, extension_update_path(update.extension, update, :update => { :reviewed => true }), :method => :put, :remote => true %>
      <% end %>

app/views/extensions/_edit_form.html.erb
<%= form_with model: extension, id: "edit-form-#{extension.id}" do |form| %>
  <% if extension.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(extension.errors.count, "error") %> prohibited this extension from being saved:</h2>

      <ul>
        <% extension.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col">
      <%= form.text_field :name, class: "form-control", placeholder: "Extension Name" %>
    </div>
    <div class="col-6">
      <%= form.text_field :url, class: "form-control", placeholder: "Extension URL" %>
    </div>
    <div class="col">
      <div class="actions">
        <%= form.submit "Update Chrome Extension", class: "btn btn-sourcecon" %>
      </div>
    </div>
  </div>
<% end %>

app/views/extensions/_extension.html.erb
<%= render :partial => 'thead', :locals => {:extension => extension} %>
<tbody class="extension-<%= extension.id %>">
  <% if @reviewed == "unreviewed" && @type == "major" %>
    <% extension.updates.unreviewed.only_majors.each do |update| %>
      <%= render :partial => 'tbody', :locals => {:update => update} %>
    <% end %>
  <% elsif @reviewed == "unreviewed" && @type == "all" %>
    <% extension.updates.unreviewed.each do |update| %>
      <%= render :partial => 'tbody', :locals => {:update => update} %>
    <% end %>
  <% elsif @reviewed == "all" && @type == "major" %>
    <% extension.updates.only_majors.each do |update| %>
      <%= render :partial => 'tbody', :locals => {:update => update} %>
    <% end %>
  <% elsif @reviewed == "all" && @type == "all" %>
    <% extension.updates.order(date: :DESC).each do |update| %>
      <%= render :partial => 'tbody', :locals => {:update => update} %>
    <% end %>
  <% end %>
</tbody>

app/views/extensions/_form.html.erb
<%= form_with model: extension, id: 'new-extension-form' do |form| %>
  <% if extension.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(extension.errors.count, "error") %> prohibited this extension from being saved:</h2>

      <ul>
        <% extension.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row my-3">
    <div class="col-sm">
      <%= form.text_field :name, class: "form-control mr-2", placeholder: "Extension Name" %>
    </div>
    <div class="col-sm">
      <%= form.text_field :url, class: "form-control mr-2", placeholder: "Extension URL" %>
    </div>
    <div class="col-sm">
      <div class="actions">
        <%= form.submit "Add", class: "btn btn-sourcecon mr-2" %>
      </div>
    </div>
  </div>
<% end %>

app/views/extensions/_table.html.erb
<thead class="thead-sourcecon" id ="table-header">      
  <tr>
    <th>Name</th>
    <th class="text-center">Version</th>
    <th class="text-center">Date Updated</th>
    <th class="text-center">Reviewed?</th>
    <th class="edit-cell"></th>
    <th class="delete-cell"></th>
  </tr>
</thead>
<%= render @extensions %>

app/views/extensions/_thead.html.erb
<thead id = "extension-head-<%= extension.id %>" class="thead-light extension-<%= extension.id %>">
  <tr>
    <th colspan="4" id = "extension-name-<%= extension.id %>"><%= link_to extension.name, extension.url, target: :_blank %></th>
    <th class="edit-cell">
      <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_extension_path(extension), remote: true %>
    </th>
    <th class="delete-cell">
      <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, extension, method: :delete, remote: true, data: { confirm: 'WARNING: This will delete this extension and all tracked versions. Are you sure?' } %>
    </th>
  </tr>
</thead>

app/views/extensions/destroy.js.erb
class_name = 'extension-<%= @extension.id %>';
function removeElementsByClass(className){
    var elements = document.getElementsByClassName(className);
    while(elements.length > 0){
        elements[0].parentNode.removeChild(elements[0]);
    }
}

removeElementsByClass(class_name);

app/views/extensions/edit.html.erb
<h1>Editing Extension</h1>

<%= render 'form', extension: @extension %>

<%= link_to 'Show', @extension %> |
<%= link_to 'Back', extensions_path %>

app/views/extensions/edit.js.erb
var id_name = 'extension-name-<%= @extension.id %>';
var thead = document.getElementById(id_name);
thead.insertAdjacentHTML('beforeend', '<%= escape_javascript(render "form", :extension => @extension) %>');
thead.innerHTML = '<%= escape_javascript(render "edit_form", :extension => @extension) %>';

app/views/extensions/index.js.erb
var buttons = document.getElementById('button-row');
var new_buttons = '<%= escape_javascript(render "buttons") %>';
buttons.innerHTML = new_buttons;
console.log(buttons);

var table = document.getElementById('extensions-table');
var new_content = '<%= escape_javascript(render "table", :extensions => @extensions) %>';
table.innerHTML = new_content;

app/views/extensions/new.html.erb
<h1>New Extension</h1>

<%= render 'form', extension: @extension %>

<%= link_to 'Back', extensions_path %>

app/views/extensions/new.js.erb
var buttons = document.getElementById('button-row');
var table = document.getElementById('table-row');
buttons.style.display = "none";
table.insertAdjacentHTML('beforebegin', '<%= escape_javascript(render "form", :extension => @extension) %>');

app/views/extensions/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @extension.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @extension.url %>
</p>

<p>
  <strong>Site:</strong>
  <%= @extension.site %>
</p>

<%= link_to 'Edit', edit_extension_path(@extension) %> |
<%= link_to 'Back', extensions_path %>

app/views/extensions/update.js.erb
var id_name = 'extension-head-<%= @extension.id %>';
var thead = document.getElementById(id_name);
var new_content = "<%= j render :partial => 'thead', :locals => { :extension => @extension } %>";
thead.innerHTML = new_content;

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SourcingExtensions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/images/sc-logo.png' %>
    <%= stylesheet_link_tag "custom" %>
    <%= javascript_include_tag "rails-ujs" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <%= link_to image_tag('/images/sc-logo.png', :class => "d-inline-block align-top", :height => "30", :width => "30") + " Sourcing Extensions", root_path, :class => "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent  " aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <% if user_signed_in? %>
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav">
              <span class="navbar-text mr-4">
                  Logged in as <strong><%= current_user.email %></strong>
                </span>
              <li class="nav-item my-2">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav">
              <li class="nav-item my-2 mx-3">
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
              </li>
              <li class="nav-item my-2 mx-3">
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              </li>
            </ul>
          <% end %>
        </div>
      </nav>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/splash.html.erb
<%= stylesheet_link_tag "pages" %>

app/views/updates/_form.html.erb
<%= form_with(model: update, local: true) do |form| %>
  <% if update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
        <% update.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :overview %>
    <%= form.text_area :overview %>
  </div>

  <div class="field">
    <%= form.label :extension_id %>
    <%= form.text_field :extension_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing Update</h1>

<%= render 'form', update: @update %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<h1>Updates</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>Date</th>
      <th>Overview</th>
      <th>Extension</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= update.version %></td>
        <td><%= update.date %></td>
        <td><%= update.overview %></td>
        <td><%= update.extension_id %></td>
        <td><%= link_to 'Show', update %></td>
        <td><%= link_to 'Edit', edit_update_path(update) %></td>
        <td><%= link_to 'Destroy', update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/updates/new.html.erb
<h1>New Update</h1>

<%= render 'form', update: @update %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<div class="card mt-3">
  <h4 class="card-header">
    <%= link_to @update.extension.name, @update.extension.url %>
  </h4>
  <div class="card-body">
    <h6 class="card-title"><strong>Version:</strong> <%= @update.version %></h6>
    <h6 class="card-text"><strong>Updated:</strong> <%= @update.date.strftime("%B %-d, %Y") %></h6>
  </div>
  <div class="card-footer text-muted">
    <h6 class="my-3 font-weight-bold">Overview:</h6>
    <%= simple_format(@update.overview) %>
  </div>
</div>

app/views/updates/update.js.erb
var id_name = 'update-row-<%= @update.id %>';
var trow = document.getElementById(id_name);
trow.classList.toggle('sourcecon-highlight');

var cb_id_name = 'checkbox-<%= @update.id %>';
var checkbox_cell = document.getElementById(cb_id_name);
checkbox_cell.innerHTML = '<%= escape_javascript(render "extensions/checkbox", :update => @update) %>';

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>